name: trigger_deployed

on:
  # workflow_dispatch is mandatory, so that Artifactory can trigger
  # the workflow through GitHub REST API.
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        type: string
        default: main
      folder:
        description: 'Folder name'
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Update data
        run: |
          npm install --no-save | grep -v 'YN0013'
          npm run data:update-time

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Scheduler
          author_email: scheduler@github.io
          message: 'Update Time Now'

